-- Migration owner is POSTGRES_USER (uap). Runtime role cannot bypass RLS or own tables.
CREATE ROLE uap_app LOGIN PASSWORD 'uap_app' NOSUPERUSER NOBYPASSRLS NOCREATEDB NOCREATEROLE;
GRANT CONNECT ON DATABASE uap TO uap_app;
GRANT USAGE ON SCHEMA public TO uap_app;
ALTER DEFAULT PRIVILEGES FOR ROLE uap IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO uap_app;
ALTER DEFAULT PRIVILEGES FOR ROLE uap IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO uap_app;
