from django.urls import path

from apps.finance.api.views import (
    AccountDetailView,
    AccountListCreateView,
    BalanceSheetView,
    CashFlowView,
    TaxSummaryView,
    GeneralLedgerView,
    GrantDetailView,
    GrantListView,
    JournalDetailView,
    JournalListCreateView,
    JournalPostView,
    JournalReverseView,
    PeriodListCreateView,
    PeriodLockView,
    PeriodReopenView,
    ProfitLossView,
    RoleListCreateView,
    SettingsView,
    TrialBalanceView,
    EquityMovementView,
    BooksExportView,
)
from apps.finance.api.asset_views import (
    AssetDepreciateView,
    AssetDisposeView,
    AssetListCreateView,
    AssetRegisterView,
    AssetWriteDownView,
)
from apps.finance.api.stock_views import (
    InventoryValuationView,
    StockAdjustView,
    StockBalanceListView,
    StockTransferView,
    WarehouseListCreateView,
)

from apps.finance.api.reminder_views import (
    ReminderListView,
    ReminderRunView,
    ReminderRuleListCreateView,
)
from apps.finance.api.workflow_views import (
    ExceptionListView,
    ExceptionResolveView,
    SavedFilterListCreateView,
    TagListCreateView,
)
from apps.finance.api.recurring_views import (
    RecurringListCreateView,
    RecurringPauseView,
    RecurringResumeView,
    RecurringRunView,
)
from apps.finance.api.bank_views import (
    BankFeedFetchView,
    BankFeedListCreateView,
    BankLineCategorizeView,
    BankLineListView,
    BankLineMatchView,
    BankReconciliationCompleteView,
    BankReconciliationCreateView,
    BankReconciliationReopenView,
    BankRuleApplyView,
    BankRuleDetailView,
    BankRuleListCreateView,
    BankStatementImportView,
)
from apps.finance.api.purchase_views import (
    APAgingView,
    BillListCreateView,
    BillPostView,
    BillPreviewView,
    BillSubmitView,
    BillApproveView,
    BillRejectView,
    ExpenseCreateView,
    PaymentRunCreateView,
    PurchaseOrderConvertView,
    PurchaseOrderListCreateView,
    VendorCreditCreateView,
    VendorPaymentCreateView,
    VendorRefundCreateView,
    VendorStatementView,
    AttachmentDownloadView,
    AttachmentListCreateView,
)
from apps.finance.api.sales_views import (
    ARAgingView,
    ContactListCreateView,
    CreditNoteListCreateView,
    ExchangeRateListCreateView,
    InvoiceListCreateView,
    InvoicePostView,
    InvoicePreviewView,
    InvoiceSubmitView,
    InvoiceApproveView,
    InvoiceRejectView,
    ItemListCreateView,
    PaymentListCreateView,
    PaymentTermListCreateView,
    QuoteConvertView,
    QuoteListCreateView,
    RefundCreateView,
    TaxRateListCreateView,
)

urlpatterns = [
    path("settings", SettingsView.as_view(), name="finance-settings"),
    path("roles", RoleListCreateView.as_view(), name="finance-roles"),
    path("grants", GrantListView.as_view(), name="finance-grants"),
    path("grants/<str:user_id>", GrantDetailView.as_view(), name="finance-grant-detail"),
    path("accounts", AccountListCreateView.as_view(), name="finance-accounts"),
    path("accounts/<str:account_id>", AccountDetailView.as_view(), name="finance-account-detail"),
    path("journals", JournalListCreateView.as_view(), name="finance-journals"),
    path("journals/<str:journal_id>", JournalDetailView.as_view(), name="finance-journal-detail"),
    path("journals/<str:journal_id>/post", JournalPostView.as_view(), name="finance-journal-post"),
    path("journals/<str:journal_id>/reverse", JournalReverseView.as_view(), name="finance-journal-reverse"),
    path("periods", PeriodListCreateView.as_view(), name="finance-periods"),
    path("periods/<str:period_id>/lock", PeriodLockView.as_view(), name="finance-period-lock"),
    path("periods/<str:period_id>/reopen", PeriodReopenView.as_view(), name="finance-period-reopen"),
    path("reports/trial-balance", TrialBalanceView.as_view(), name="finance-trial-balance"),
    path("reports/general-ledger", GeneralLedgerView.as_view(), name="finance-general-ledger"),
    path("reports/profit-loss", ProfitLossView.as_view(), name="finance-profit-loss"),
    path("reports/balance-sheet", BalanceSheetView.as_view(), name="finance-balance-sheet"),
    path("reports/cash-flow", CashFlowView.as_view(), name="finance-cash-flow"),
    path("reports/tax-summary", TaxSummaryView.as_view(), name="finance-tax-summary"),
    path("reports/equity-movement", EquityMovementView.as_view(), name="finance-equity-movement"),
    path("export", BooksExportView.as_view(), name="finance-export"),
    path("reports/inventory-valuation", InventoryValuationView.as_view(), name="finance-inventory-valuation"),
    path("reports/asset-register", AssetRegisterView.as_view(), name="finance-asset-register"),
    path("reports/ar-aging", ARAgingView.as_view(), name="finance-ar-aging"),
    path("reports/ap-aging", APAgingView.as_view(), name="finance-ap-aging"),
    path("contacts", ContactListCreateView.as_view(), name="finance-contacts"),
    path("items", ItemListCreateView.as_view(), name="finance-items"),
    path("tax-rates", TaxRateListCreateView.as_view(), name="finance-tax-rates"),
    path("payment-terms", PaymentTermListCreateView.as_view(), name="finance-payment-terms"),
    path("exchange-rates", ExchangeRateListCreateView.as_view(), name="finance-exchange-rates"),
    path("quotes", QuoteListCreateView.as_view(), name="finance-quotes"),
    path("quotes/<str:quote_id>/convert", QuoteConvertView.as_view(), name="finance-quote-convert"),
    path("invoices", InvoiceListCreateView.as_view(), name="finance-invoices"),
    path("invoices/<str:invoice_id>/preview", InvoicePreviewView.as_view(), name="finance-invoice-preview"),
    path("invoices/<str:invoice_id>/post", InvoicePostView.as_view(), name="finance-invoice-post"),
    path("invoices/<str:invoice_id>/submit", InvoiceSubmitView.as_view(), name="finance-invoice-submit"),
    path("invoices/<str:invoice_id>/approve", InvoiceApproveView.as_view(), name="finance-invoice-approve"),
    path("invoices/<str:invoice_id>/reject", InvoiceRejectView.as_view(), name="finance-invoice-reject"),
    path("credit-notes", CreditNoteListCreateView.as_view(), name="finance-credit-notes"),
    path("payments", PaymentListCreateView.as_view(), name="finance-payments"),
    path("refunds", RefundCreateView.as_view(), name="finance-refunds"),
    path("bills", BillListCreateView.as_view(), name="finance-bills"),
    path("bills/<str:bill_id>/preview", BillPreviewView.as_view(), name="finance-bill-preview"),
    path("bills/<str:bill_id>/post", BillPostView.as_view(), name="finance-bill-post"),
    path("bills/<str:bill_id>/submit", BillSubmitView.as_view(), name="finance-bill-submit"),
    path("bills/<str:bill_id>/approve", BillApproveView.as_view(), name="finance-bill-approve"),
    path("bills/<str:bill_id>/reject", BillRejectView.as_view(), name="finance-bill-reject"),
    path("vendor-credits", VendorCreditCreateView.as_view(), name="finance-vendor-credits"),
    path("vendor-payments", VendorPaymentCreateView.as_view(), name="finance-vendor-payments"),
    path("vendor-refunds", VendorRefundCreateView.as_view(), name="finance-vendor-refunds"),
    path("expenses", ExpenseCreateView.as_view(), name="finance-expenses"),
    path("purchase-orders", PurchaseOrderListCreateView.as_view(), name="finance-purchase-orders"),
    path("purchase-orders/<str:po_id>/convert", PurchaseOrderConvertView.as_view(), name="finance-po-convert"),
    path("payment-runs", PaymentRunCreateView.as_view(), name="finance-payment-runs"),
    path("contacts/<str:contact_id>/vendor-statement", VendorStatementView.as_view(), name="finance-vendor-statement"),
    path("attachments", AttachmentListCreateView.as_view(), name="finance-attachments"),
    path("attachments/<str:attachment_id>/download", AttachmentDownloadView.as_view(), name="finance-attachment-download"),
    path("bank-statements", BankStatementImportView.as_view(), name="finance-bank-statements"),
    path("bank-lines", BankLineListView.as_view(), name="finance-bank-lines"),
    path("bank-lines/<str:line_id>/match", BankLineMatchView.as_view(), name="finance-bank-line-match"),
    path("bank-lines/<str:line_id>/categorize", BankLineCategorizeView.as_view(), name="finance-bank-line-categorize"),
    path("bank-reconciliations", BankReconciliationCreateView.as_view(), name="finance-bank-reconciliations"),
    path("bank-reconciliations/<str:recon_id>/complete", BankReconciliationCompleteView.as_view(), name="finance-bank-recon-complete"),
    path("bank-reconciliations/<str:recon_id>/reopen", BankReconciliationReopenView.as_view(), name="finance-bank-recon-reopen"),
    path("bank-rules", BankRuleListCreateView.as_view(), name="finance-bank-rules"),
    path("bank-rules/apply", BankRuleApplyView.as_view(), name="finance-bank-rules-apply"),
    path("bank-rules/<str:rule_id>", BankRuleDetailView.as_view(), name="finance-bank-rule-detail"),
    path("bank-feeds", BankFeedListCreateView.as_view(), name="finance-bank-feeds"),
    path("bank-feeds/<str:feed_id>/fetch", BankFeedFetchView.as_view(), name="finance-bank-feed-fetch"),
    path("recurring", RecurringListCreateView.as_view(), name="finance-recurring"),
    path("recurring/run", RecurringRunView.as_view(), name="finance-recurring-run"),
    path("recurring/<str:schedule_id>/pause", RecurringPauseView.as_view(), name="finance-recurring-pause"),
    path("recurring/<str:schedule_id>/resume", RecurringResumeView.as_view(), name="finance-recurring-resume"),
    path("reminder-rules", ReminderRuleListCreateView.as_view(), name="finance-reminder-rules"),
    path("reminders", ReminderListView.as_view(), name="finance-reminders"),
    path("reminders/run", ReminderRunView.as_view(), name="finance-reminders-run"),
    path("saved-filters", SavedFilterListCreateView.as_view(), name="finance-saved-filters"),
    path("tags", TagListCreateView.as_view(), name="finance-tags"),
    path("exceptions", ExceptionListView.as_view(), name="finance-exceptions"),
    path("exceptions/<str:exception_id>/resolve", ExceptionResolveView.as_view(), name="finance-exception-resolve"),
    path("warehouses", WarehouseListCreateView.as_view(), name="finance-warehouses"),
    path("stock/balances", StockBalanceListView.as_view(), name="finance-stock-balances"),
    path("stock/adjust", StockAdjustView.as_view(), name="finance-stock-adjust"),
    path("stock/transfer", StockTransferView.as_view(), name="finance-stock-transfer"),
    path("assets/depreciate", AssetDepreciateView.as_view(), name="finance-asset-depreciate"),
    path("assets", AssetListCreateView.as_view(), name="finance-assets"),
    path("assets/<str:asset_id>/write-down", AssetWriteDownView.as_view(), name="finance-asset-write-down"),
    path("assets/<str:asset_id>/dispose", AssetDisposeView.as_view(), name="finance-asset-dispose"),
]
