# Generated by Django 5.2.17 on 2026-09-16 09:20

import apps.authentication.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tenancy_organization',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='tenancy.organization')),
            ],
            options={
                'db_table': 'tenancy_location',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=36)),
                ('roles', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('suspended', 'Suspended'), ('removed', 'Removed')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='tenancy.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='tenancy.organization')),
            ],
            options={
                'db_table': 'tenancy_membership',
                'constraints': [models.UniqueConstraint(fields=('user_id', 'organization'), name='uniq_membership_user_org')],
            },
        ),
    ]
