# Generated by Django 5.2.17 on 2026-09-17 07:17

import apps.authentication.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('exponent', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'finance_currency',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('classification', models.CharField(choices=[('asset', 'Asset'), ('liability', 'Liability'), ('equity', 'Equity'), ('income', 'Income'), ('expense', 'Expense')], max_length=16)),
                ('is_control', models.BooleanField(default=False)),
                ('control_kind', models.CharField(blank=True, default='', max_length=8)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_account',
            },
        ),
        migrations.CreateModel(
            name='DocumentSequence',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=32)),
                ('series', models.CharField(default='default', max_length=32)),
                ('prefix', models.CharField(blank=True, default='JE-', max_length=16)),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_sequences', to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_document_sequence',
            },
        ),
        migrations.CreateModel(
            name='FinanceAuditEvent',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('actor_user_id', models.CharField(max_length=36)),
                ('action', models.CharField(max_length=64)),
                ('object_type', models.CharField(max_length=32)),
                ('object_id', models.CharField(blank=True, default='', max_length=36)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_audit_event',
            },
        ),
        migrations.CreateModel(
            name='FinanceRole',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('slug', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=100)),
                ('permissions', models.JSONField(default=list)),
                ('is_preset', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_roles', to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_role',
            },
        ),
        migrations.CreateModel(
            name='FinanceGrant',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('user_id', models.CharField(db_index=True, max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finance_grants', to='tenancy.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grants', to='finance.financerole')),
            ],
            options={
                'db_table': 'finance_grant',
            },
        ),
        migrations.CreateModel(
            name='FinanceSettings',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, related_name='finance_settings', serialize=False, to='tenancy.organization')),
                ('country_code', models.CharField(max_length=2)),
                ('fiscal_year_start_month', models.PositiveSmallIntegerField()),
                ('timezone', models.CharField(max_length=64)),
                ('locale', models.CharField(default='en', max_length=32)),
                ('tax_registration_applies', models.BooleanField(default=False)),
                ('setup_completed_at', models.DateTimeField()),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
            ],
            options={
                'db_table': 'finance_settings',
            },
        ),
        migrations.CreateModel(
            name='FiscalPeriodLock',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('start_on', models.DateField()),
                ('end_on', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('locked', 'Locked')], default='open', max_length=16)),
                ('locked_by', models.CharField(blank=True, default='', max_length=36)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('reopen_reason', models.TextField(blank=True, default='')),
                ('reopened_by', models.CharField(blank=True, default='', max_length=36)),
                ('reopened_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='period_locks', to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_period_lock',
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=16)),
                ('entry_date', models.DateField()),
                ('number', models.CharField(blank=True, default='', max_length=32)),
                ('memo', models.TextField(blank=True, default='')),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('opening', 'Opening')], default='manual', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('posted_by', models.CharField(blank=True, default='', max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journals', to='tenancy.organization')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_source', to='finance.journalentry')),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversal_of', to='finance.journalentry')),
            ],
            options={
                'db_table': 'finance_journal',
            },
        ),
        migrations.CreateModel(
            name='FinanceIdempotency',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=64)),
                ('key', models.CharField(max_length=128)),
                ('request_hash', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.organization')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.journalentry')),
            ],
            options={
                'db_table': 'finance_idempotency',
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('debit', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('credit', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_journal_line',
            },
        ),
        migrations.AddConstraint(
            model_name='account',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='uniq_finance_account_org_code'),
        ),
        migrations.AddConstraint(
            model_name='documentsequence',
            constraint=models.UniqueConstraint(fields=('organization', 'document_type', 'series'), name='uniq_finance_sequence'),
        ),
        migrations.AddConstraint(
            model_name='financerole',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='uniq_finance_role_org_slug'),
        ),
        migrations.AddConstraint(
            model_name='financegrant',
            constraint=models.UniqueConstraint(fields=('organization', 'user_id'), name='uniq_finance_grant_org_user'),
        ),
        migrations.AddConstraint(
            model_name='financeidempotency',
            constraint=models.UniqueConstraint(fields=('organization', 'operation', 'key'), name='uniq_finance_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='journalline',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('credit', 0), ('debit__gt', 0)), models.Q(('credit__gt', 0), ('debit', 0)), _connector='OR'), name='journal_line_debit_xor_credit'),
        ),
    ]
