# Generated by Django 5.2.17 on 2026-09-17 07:36

import apps.authentication.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_seed_and_rls'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='advance_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='ar_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='fx_gain_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='fx_loss_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('opening', 'Opening'), ('invoice', 'Invoice'), ('payment', 'Payment'), ('credit', 'Credit'), ('refund', 'Refund')], default='manual', max_length=16),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_customer', models.BooleanField(default=True)),
                ('email', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='active', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_contact',
            },
        ),
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=16)),
                ('number', models.CharField(blank=True, default='', max_length=32)),
                ('entry_date', models.DateField()),
                ('fx_rate', models.DecimalField(decimal_places=8, default=1, max_digits=20)),
                ('total', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('base_total', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.contact')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_credit_note',
            },
        ),
        migrations.CreateModel(
            name='CreditNoteLine',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('net', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('base_net', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('base_tax', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('base_total', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('credit_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.creditnote')),
                ('income_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('tax_payable_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account')),
            ],
            options={
                'db_table': 'finance_credit_note_line',
            },
        ),
        migrations.CreateModel(
            name='CustomerPayment',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=16)),
                ('entry_date', models.DateField()),
                ('fx_rate', models.DecimalField(decimal_places=8, default=1, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.contact')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_customer_payment',
            },
        ),
        migrations.CreateModel(
            name='CustomerRefund',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('entry_date', models.DateField()),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.customerpayment')),
            ],
            options={
                'db_table': 'finance_customer_refund',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=16)),
                ('number', models.CharField(blank=True, default='', max_length=32)),
                ('entry_date', models.DateField()),
                ('due_date', models.DateField()),
                ('fx_rate', models.DecimalField(decimal_places=8, default=1, max_digits=20)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('total', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('base_total', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.contact')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_invoice',
            },
        ),
        migrations.AddField(
            model_name='creditnote',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.invoice'),
        ),
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('base_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('entry_date', models.DateField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('credit_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.creditnote')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.customerpayment')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.invoice')),
            ],
            options={
                'db_table': 'finance_allocation',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('kind', models.CharField(choices=[('service', 'Service'), ('good', 'Good')], default='service', max_length=16)),
                ('unit_price', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('status', models.CharField(default='active', max_length=16)),
                ('version', models.PositiveIntegerField(default=1)),
                ('income_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_item',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('unit_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('tax_rate_id_snap', models.CharField(blank=True, default='', max_length=36)),
                ('tax_rate_value', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('tax_method', models.CharField(default='exclusive', max_length=16)),
                ('tax_name', models.CharField(blank=True, default='', max_length=100)),
                ('net', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('base_net', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('base_tax', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('base_total', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('income_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.item')),
            ],
            options={
                'db_table': 'finance_invoice_line',
            },
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('days', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_payment_term',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('converted', 'Converted')], default='draft', max_length=16)),
                ('entry_date', models.DateField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.contact')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_quote',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.quote'),
        ),
        migrations.CreateModel(
            name='TaxRate',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=10)),
                ('method', models.CharField(choices=[('exclusive', 'Exclusive'), ('inclusive', 'Inclusive')], default='exclusive', max_length=16)),
                ('valid_from', models.DateField()),
                ('status', models.CharField(default='active', max_length=16)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('payable_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
            ],
            options={
                'db_table': 'finance_tax_rate',
            },
        ),
        migrations.CreateModel(
            name='QuoteLine',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=8, default=1, max_digits=20)),
                ('unit_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.item')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.quote')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.taxrate')),
            ],
            options={
                'db_table': 'finance_quote_line',
            },
        ),
        migrations.AddField(
            model_name='item',
            name='default_tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.taxrate'),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=8, max_digits=20)),
                ('as_of', models.DateField()),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_exchange_rate',
                'constraints': [models.UniqueConstraint(fields=('organization', 'currency', 'as_of'), name='uniq_finance_fx_rate')],
            },
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('organization', 'sku'), name='uniq_finance_item_sku'),
        ),
    ]
