# Generated by Django 5.2.17 on 2026-09-17 07:51

import apps.authentication.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_sales_rls'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_vendor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='ap_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='vendor_advance_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account'),
        ),
        migrations.AddField(
            model_name='item',
            name='expense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('opening', 'Opening'), ('invoice', 'Invoice'), ('payment', 'Payment'), ('credit', 'Credit'), ('refund', 'Refund'), ('bill', 'Bill'), ('expense', 'Expense'), ('vendor_payment', 'Vendor Payment'), ('vendor_credit', 'Vendor Credit'), ('vendor_refund', 'Vendor Refund')], default='manual', max_length=16),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=16)),
                ('number', models.CharField(blank=True, default='', max_length=32)),
                ('entry_date', models.DateField()),
                ('due_date', models.DateField()),
                ('fx_rate', models.DecimalField(decimal_places=8, default=1, max_digits=20)),
                ('contact_name', models.CharField(blank=True, default='', max_length=255)),
                ('total', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('base_total', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.contact')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_bill',
            },
        ),
        migrations.CreateModel(
            name='BillLine',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('unit_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('tax_rate_id_snap', models.CharField(blank=True, default='', max_length=36)),
                ('tax_rate_value', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('tax_method', models.CharField(default='exclusive', max_length=16)),
                ('tax_name', models.CharField(blank=True, default='', max_length=100)),
                ('net', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('base_net', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('base_tax', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('base_total', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.bill')),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.item')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_bill_line',
            },
        ),
        migrations.CreateModel(
            name='PaidExpense',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('number', models.CharField(blank=True, default='', max_length=32)),
                ('entry_date', models.DateField()),
                ('fx_rate', models.DecimalField(decimal_places=8, default=1, max_digits=20)),
                ('total', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('base_total', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.contact')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_paid_expense',
            },
        ),
        migrations.CreateModel(
            name='PaidExpenseLine',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('net', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('base_net', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('base_tax', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('base_total', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.paidexpense')),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('tax_payable_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account')),
            ],
            options={
                'db_table': 'finance_paid_expense_line',
            },
        ),
        migrations.CreateModel(
            name='VendorCredit',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=16)),
                ('number', models.CharField(blank=True, default='', max_length=32)),
                ('entry_date', models.DateField()),
                ('fx_rate', models.DecimalField(decimal_places=8, default=1, max_digits=20)),
                ('total', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('base_total', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.bill')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.contact')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_vendor_credit',
            },
        ),
        migrations.CreateModel(
            name='VendorCreditLine',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('net', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('tax_amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('total', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('base_net', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('base_tax', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('base_total', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.vendorcredit')),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('tax_payable_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account')),
            ],
            options={
                'db_table': 'finance_vendor_credit_line',
            },
        ),
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=16)),
                ('entry_date', models.DateField()),
                ('fx_rate', models.DecimalField(decimal_places=8, default=1, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.contact')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_vendor_payment',
            },
        ),
        migrations.CreateModel(
            name='BillAllocation',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('base_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('entry_date', models.DateField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.bill')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('credit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.vendorcredit')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.vendorpayment')),
            ],
            options={
                'db_table': 'finance_bill_allocation',
            },
        ),
        migrations.CreateModel(
            name='VendorRefund',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('entry_date', models.DateField()),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.vendorpayment')),
            ],
            options={
                'db_table': 'finance_vendor_refund',
            },
        ),
    ]
