# Generated by Django 5.2.17 on 2026-09-17 07:58

import apps.authentication.ids
import apps.finance.models.attachments
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_purchases_rls'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceAttachment',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('object_type', models.CharField(max_length=32)),
                ('object_id', models.CharField(max_length=36)),
                ('original_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=64)),
                ('size', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to=apps.finance.models.attachments._upload_to)),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_attachment',
            },
        ),
        migrations.CreateModel(
            name='PaymentRun',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=16)),
                ('entry_date', models.DateField()),
                ('number', models.CharField(blank=True, default='', max_length=32)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_payment_run',
            },
        ),
        migrations.CreateModel(
            name='PaymentRunLine',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.bill')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.vendorpayment')),
                ('payment_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.paymentrun')),
            ],
            options={
                'db_table': 'finance_payment_run_line',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('converted', 'Converted')], default='draft', max_length=16)),
                ('entry_date', models.DateField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.contact')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_purchase_order',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.purchaseorder'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=8, default=1, max_digits=20)),
                ('unit_price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.item')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.purchaseorder')),
                ('tax_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.taxrate')),
            ],
            options={
                'db_table': 'finance_purchase_order_line',
            },
        ),
        migrations.AddConstraint(
            model_name='paymentrun',
            constraint=models.UniqueConstraint(fields=('organization', 'idempotency_key'), name='uniq_finance_payment_run_key'),
        ),
    ]
