# Generated by Django 5.2.17 on 2026-09-17 08:06

import apps.authentication.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_po_attachment_rls'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('opening', 'Opening'), ('invoice', 'Invoice'), ('payment', 'Payment'), ('credit', 'Credit'), ('refund', 'Refund'), ('bill', 'Bill'), ('expense', 'Expense'), ('vendor_payment', 'Vendor Payment'), ('vendor_credit', 'Vendor Credit'), ('vendor_refund', 'Vendor Refund'), ('bank', 'Bank')], default='manual', max_length=16),
        ),
        migrations.CreateModel(
            name='BankReconciliation',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('start_on', models.DateField()),
                ('end_on', models.DateField()),
                ('opening', models.DecimalField(decimal_places=8, max_digits=20)),
                ('closing', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('complete', 'Complete')], default='open', max_length=16)),
                ('reopen_reason', models.TextField(blank=True, default='')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_bank_reconciliation',
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('original_name', models.CharField(blank=True, default='', max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_bank_statement',
            },
        ),
        migrations.CreateModel(
            name='BankLine',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('entry_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('fingerprint', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('imported', 'Imported'), ('matched', 'Matched'), ('categorized', 'Categorized')], default='imported', max_length=16)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('customer_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.customerpayment')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('vendor_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.vendorpayment')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.bankstatement')),
            ],
            options={
                'db_table': 'finance_bank_line',
                'constraints': [models.UniqueConstraint(fields=('organization', 'account', 'fingerprint'), name='uniq_finance_bank_line_fingerprint'), models.UniqueConstraint(condition=models.Q(('customer_payment__isnull', False)), fields=('customer_payment',), name='uniq_finance_bank_line_customer_payment'), models.UniqueConstraint(condition=models.Q(('vendor_payment__isnull', False)), fields=('vendor_payment',), name='uniq_finance_bank_line_vendor_payment')],
            },
        ),
    ]
