# Generated by Django 5.2.17 on 2026-09-17 08:14

import apps.authentication.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_banking_rls'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringSchedule',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('invoice', 'Invoice'), ('bill', 'Bill'), ('expense', 'Expense')], max_length=16)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=16)),
                ('day_of_month', models.PositiveSmallIntegerField()),
                ('start_on', models.DateField()),
                ('next_on', models.DateField()),
                ('end_on', models.DateField(blank=True, null=True)),
                ('fx_rate', models.DecimalField(decimal_places=8, default=1, max_digits=20)),
                ('lines', models.JSONField(default=list)),
                ('created_by', models.CharField(blank=True, default='', max_length=36)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.contact')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.currency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_recurring_schedule',
            },
        ),
        migrations.CreateModel(
            name='RecurringOccurrence',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('occurs_on', models.DateField()),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.bill')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.paidexpense')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.invoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='finance.recurringschedule')),
            ],
            options={
                'db_table': 'finance_recurring_occurrence',
                'constraints': [models.UniqueConstraint(fields=('schedule', 'occurs_on'), name='uniq_finance_recurring_occurrence')],
            },
        ),
    ]
