# Generated by Django 5.2.17 on 2026-09-17 08:23

import apps.authentication.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_recurring_rls'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='approved_by',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='bill',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='allow_self_approve',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='require_document_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='approved_by',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='recurringschedule',
            name='auto_post',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recurringschedule',
            name='frequency',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('weekly', 'Weekly'), ('yearly', 'Yearly')], default='monthly', max_length=16),
        ),
        migrations.AddField(
            model_name='recurringschedule',
            name='month_of_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recurringschedule',
            name='weekday',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('posted', 'Posted')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('posted', 'Posted')], default='draft', max_length=16),
        ),
        migrations.AlterField(
            model_name='recurringschedule',
            name='day_of_month',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('document_kind', models.CharField(max_length=16)),
                ('days_before_due', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_reminder_rule',
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('object_type', models.CharField(max_length=16)),
                ('object_id', models.CharField(max_length=36)),
                ('due_date', models.DateField()),
                ('as_of', models.DateField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='finance.reminderrule')),
            ],
            options={
                'db_table': 'finance_reminder',
                'constraints': [models.UniqueConstraint(fields=('rule', 'object_id', 'due_date'), name='uniq_finance_reminder')],
            },
        ),
    ]
