# Generated by Django 5.2.17 on 2026-09-17 08:27

import apps.authentication.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_automation_rls'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankRule',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('pattern', models.CharField(max_length=255)),
                ('direction', models.CharField(choices=[('any', 'Any'), ('inflow', 'Inflow'), ('outflow', 'Outflow')], default='any', max_length=16)),
                ('priority', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_bank_rule',
            },
        ),
    ]
