# Generated by Django 5.2.17 on 2026-09-17 08:47

import apps.authentication.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_bank_rules_rls'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankrule',
            name='amount_max',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='bankrule',
            name='amount_min',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='bankrule',
            name='match_kind',
            field=models.CharField(choices=[('contains', 'Contains'), ('regex', 'Regex')], default='contains', max_length=16),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='approval_levels',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='approval_threshold',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='reminder',
            name='emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BankFeed',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500)),
                ('active', models.BooleanField(default=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_bank_feed',
            },
        ),
        migrations.CreateModel(
            name='FinanceException',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=64)),
                ('object_type', models.CharField(blank=True, default='', max_length=32)),
                ('object_id', models.CharField(blank=True, default='', max_length=36)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_exception',
            },
        ),
        migrations.CreateModel(
            name='ApprovalAction',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('object_type', models.CharField(max_length=16)),
                ('object_id', models.CharField(max_length=36)),
                ('actor_user_id', models.CharField(max_length=36)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_approval_action',
                'constraints': [models.UniqueConstraint(fields=('object_type', 'object_id', 'actor_user_id'), name='uniq_finance_approval_action')],
            },
        ),
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('resource', models.CharField(max_length=32)),
                ('params', models.JSONField(default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_saved_filter',
                'constraints': [models.UniqueConstraint(fields=('organization', 'resource', 'name'), name='uniq_finance_saved_filter')],
            },
        ),
    ]
