# Generated by Django 5.2.17 on 2026-09-17 08:55

import apps.authentication.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_phase5_rls'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='cogs_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account'),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='inventory_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account'),
        ),
        migrations.AddField(
            model_name='item',
            name='tracked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('opening', 'Opening'), ('invoice', 'Invoice'), ('payment', 'Payment'), ('credit', 'Credit'), ('refund', 'Refund'), ('bill', 'Bill'), ('expense', 'Expense'), ('vendor_payment', 'Vendor Payment'), ('vendor_credit', 'Vendor Credit'), ('vendor_refund', 'Vendor Refund'), ('bank', 'Bank'), ('stock', 'Stock')], default='manual', max_length=16),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_warehouse',
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('receive', 'Receive'), ('issue', 'Issue'), ('adjust', 'Adjust'), ('transfer', 'Transfer')], max_length=16)),
                ('qty', models.DecimalField(decimal_places=8, max_digits=20)),
                ('unit_cost', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('value', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('source_type', models.CharField(blank=True, default='', max_length=16)),
                ('source_id', models.CharField(blank=True, default='', max_length=36)),
                ('entry_date', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.item')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.warehouse')),
            ],
            options={
                'db_table': 'finance_stock_move',
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('qty', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('value', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.item')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.warehouse')),
            ],
            options={
                'db_table': 'finance_stock_balance',
            },
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_finance_warehouse_name'),
        ),
        migrations.AddConstraint(
            model_name='stockbalance',
            constraint=models.UniqueConstraint(fields=('warehouse', 'item'), name='uniq_finance_stock_balance'),
        ),
    ]
