# Generated by Django 5.2.17 on 2026-09-17 09:08

import apps.authentication.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0020_inventory_rls'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('opening', 'Opening'), ('invoice', 'Invoice'), ('payment', 'Payment'), ('credit', 'Credit'), ('refund', 'Refund'), ('bill', 'Bill'), ('expense', 'Expense'), ('vendor_payment', 'Vendor Payment'), ('vendor_credit', 'Vendor Credit'), ('vendor_refund', 'Vendor Refund'), ('bank', 'Bank'), ('stock', 'Stock'), ('asset', 'Asset')], default='manual', max_length=16),
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('cost', models.DecimalField(decimal_places=8, max_digits=20)),
                ('residual', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('life_months', models.PositiveIntegerField()),
                ('in_service_date', models.DateField()),
                ('accum', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disposed', 'Disposed')], default='active', max_length=16)),
                ('disposed_on', models.DateField(blank=True, null=True)),
                ('accum_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account')),
                ('cost_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account')),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_fixed_asset',
            },
        ),
        migrations.CreateModel(
            name='AssetCharge',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('depreciate', 'Depreciate'), ('write_down', 'Write Down')], max_length=16)),
                ('period', models.DateField()),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', to='finance.fixedasset')),
            ],
            options={
                'db_table': 'finance_asset_charge',
            },
        ),
        migrations.AddConstraint(
            model_name='fixedasset',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='uniq_finance_fixed_asset_number'),
        ),
        migrations.AddConstraint(
            model_name='assetcharge',
            constraint=models.UniqueConstraint(fields=('asset', 'kind', 'period'), name='uniq_finance_asset_charge'),
        ),
    ]
