# Generated by Django 5.2.17 on 2026-09-17 09:15

import apps.authentication.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0022_fixed_assets_rls'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cashflow_kind',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.CreateModel(
            name='ReportingTag',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_reporting_tag',
            },
        ),
        migrations.AddField(
            model_name='journalline',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.reportingtag'),
        ),
        migrations.AddConstraint(
            model_name='reportingtag',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='uniq_finance_reporting_tag'),
        ),
    ]
