# Generated by Django 5.2.17 on 2026-09-18 06:01

import django.db.models.deletion
from django.db import migrations, models

from apps.finance.models.config import ISO_CURRENCIES


def seed_currencies(apps, schema_editor):
    Currency = apps.get_model("finance", "Currency")
    Currency.objects.bulk_create(
        [Currency(code=code, exponent=exp, name=name) for code, exp, name in ISO_CURRENCIES],
        ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_cashflow_tags_rls'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bankline',
            name='uniq_finance_bank_line_fingerprint',
        ),
        migrations.AddField(
            model_name='bankreconciliation',
            name='book_balance',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='bankstatement',
            name='file_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='creditnoteline',
            name='invoice_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_lines', to='finance.invoiceline'),
        ),
        migrations.AddField(
            model_name='creditnoteline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.item'),
        ),
        migrations.AddField(
            model_name='creditnoteline',
            name='price_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='creditnoteline',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='financeidempotency',
            name='resource_id',
            field=models.CharField(blank=True, default='', max_length=36),
        ),
        migrations.AddField(
            model_name='financeidempotency',
            name='resource_type',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='vendorcreditline',
            name='bill_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_lines', to='finance.billline'),
        ),
        migrations.AddField(
            model_name='vendorcreditline',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.item'),
        ),
        migrations.AddField(
            model_name='vendorcreditline',
            name='price_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendorcreditline',
            name='quantity',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='bankline',
            name='status',
            field=models.CharField(choices=[('imported', 'Imported'), ('matched', 'Matched'), ('categorized', 'Categorized'), ('review', 'Review')], default='imported', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='bankstatement',
            constraint=models.UniqueConstraint(condition=models.Q(('file_hash', ''), _negated=True), fields=('organization', 'account', 'file_hash'), name='uniq_finance_bank_statement_hash'),
        ),
        migrations.RunPython(seed_currencies, migrations.RunPython.noop),
    ]
