# Generated by Django 5.2.17 on 2026-09-18 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_production_remediation'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankline',
            name='parser_version',
            field=models.CharField(blank=True, default='1', max_length=16),
        ),
        migrations.AddField(
            model_name='bankline',
            name='raw',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='bankline',
            name='review_reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='bankline',
            name='source_row',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='financeidempotency',
            name='status',
            field=models.CharField(default='in_progress', max_length=24),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='retained_earnings_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('opening', 'Opening'), ('invoice', 'Invoice'), ('payment', 'Payment'), ('credit', 'Credit'), ('refund', 'Refund'), ('bill', 'Bill'), ('expense', 'Expense'), ('vendor_payment', 'Vendor Payment'), ('vendor_credit', 'Vendor Credit'), ('vendor_refund', 'Vendor Refund'), ('bank', 'Bank'), ('stock', 'Stock'), ('asset', 'Asset'), ('close', 'Close')], default='manual', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='allocation',
            constraint=models.UniqueConstraint(condition=models.Q(('payment__isnull', False)), fields=('payment', 'invoice'), name='uniq_finance_allocation_payment_invoice'),
        ),
        migrations.AddConstraint(
            model_name='billallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('payment__isnull', False)), fields=('payment', 'bill'), name='uniq_finance_bill_allocation_payment_bill'),
        ),
    ]
