# Generated by Django 5.2.17 on 2026-09-18 06:47

import apps.authentication.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0026_year_close_and_constraints'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billline',
            name='tax_components',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='billline',
            name='tax_kind',
            field=models.CharField(blank=True, default='standard', max_length=16),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='tax_components',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='tax_kind',
            field=models.CharField(blank=True, default='standard', max_length=16),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='compound_base',
            field=models.CharField(default='running', max_length=16),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='compound_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compounds', to='finance.taxrate'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='kind',
            field=models.CharField(default='standard', max_length=16),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='recoverable_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account'),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='recoverable_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=10),
        ),
        migrations.AddField(
            model_name='taxrate',
            name='valid_to',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FinanceCountryPack',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=16)),
                ('enabled', models.BooleanField(default=False)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.CharField(blank=True, default='', max_length=36)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_country_pack',
                'constraints': [models.UniqueConstraint(fields=('organization', 'country_code'), name='uniq_finance_country_pack')],
            },
        ),
    ]
