# Generated by Django 5.2.17 on 2026-09-18 07:01

import apps.authentication.ids
import django.db.models.deletion
from pathlib import Path
from django.db import migrations, models


def apply_rls(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    sql_path = Path(__file__).resolve().parents[1] / "sql" / "rls.sql"
    lines = [line for line in sql_path.read_text(encoding="utf-8").splitlines() if not line.strip().startswith("--")]
    statements = [stmt.strip() for stmt in "\n".join(lines).split(";") if stmt.strip()]
    with schema_editor.connection.cursor() as cursor:
        for stmt in statements:
            cursor.execute(stmt)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0027_tax_engine_country_pack'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financesettings',
            name='cutover_mode',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='financesettings',
            name='cutover_stage',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('opening', 'Opening'), ('invoice', 'Invoice'), ('payment', 'Payment'), ('credit', 'Credit'), ('refund', 'Refund'), ('bill', 'Bill'), ('expense', 'Expense'), ('vendor_payment', 'Vendor Payment'), ('vendor_credit', 'Vendor Credit'), ('vendor_refund', 'Vendor Refund'), ('bank', 'Bank'), ('stock', 'Stock'), ('asset', 'Asset'), ('close', 'Close'), ('fx_reval', 'Fx Reval'), ('adjust', 'Adjust')], default='manual', max_length=16),
        ),
        migrations.CreateModel(
            name='FinanceAdjustment',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=16)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('entry_date', models.DateField()),
                ('reverse_on', models.DateField()),
                ('memo', models.CharField(blank=True, default='', max_length=255)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.account')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.organization')),
                ('reverse_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.journalentry')),
            ],
            options={
                'db_table': 'finance_adjustment',
            },
        ),
        migrations.CreateModel(
            name='FinanceWebhookEndpoint',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=500)),
                ('secret', models.CharField(max_length=64)),
                ('events', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.organization')),
            ],
            options={
                'db_table': 'finance_webhook_endpoint',
            },
        ),
        migrations.CreateModel(
            name='FinanceFxReval',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('as_of', models.DateField()),
                ('amount', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.journalentry')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.organization')),
                ('reverse_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='finance.journalentry')),
            ],
            options={
                'db_table': 'finance_fx_reval',
                'constraints': [models.UniqueConstraint(fields=('organization', 'as_of'), name='uniq_finance_fx_reval')],
            },
        ),
        migrations.CreateModel(
            name='FinanceWebhookDelivery',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=36)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('dead', 'Dead')], default='pending', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt', models.DateTimeField()),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.organization')),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.financewebhookendpoint')),
            ],
            options={
                'db_table': 'finance_webhook_delivery',
                'constraints': [models.UniqueConstraint(fields=('organization', 'event_id'), name='uniq_finance_webhook_event')],
            },
        ),
        migrations.RunPython(apply_rls, migrations.RunPython.noop),
    ]
