# Generated by Django 5.2.17 on 2026-09-16 09:45

import apps.authentication.ids
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('clerk_user_id', models.CharField(max_length=64, unique=True)),
                ('primary_email_hash', models.CharField(db_index=True, max_length=64)),
                ('primary_email_ciphertext', models.TextField(blank=True, default='')),
                ('first_name', models.CharField(blank=True, default='', max_length=150)),
                ('last_name', models.CharField(blank=True, default='', max_length=150)),
                ('avatar_url', models.TextField(blank=True, default='')),
                ('email_verified', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('deleted', 'Deleted')], default='active', max_length=20)),
                ('authorization_version', models.BigIntegerField(default=1)),
                ('timezone', models.CharField(blank=True, default='', max_length=64)),
                ('locale', models.CharField(blank=True, default='', max_length=20)),
                ('last_authenticated_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'app_auth_user',
                'indexes': [models.Index(fields=['status', 'created_at'], name='app_auth_us_status_452540_idx'), models.Index(fields=['authorization_version'], name='app_auth_us_authori_d7c6c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128)),
                ('key_hash', models.CharField(blank=True, default='', max_length=64)),
                ('user_id', models.CharField(blank=True, default='', max_length=36)),
                ('method', models.CharField(blank=True, default='', max_length=10)),
                ('path', models.CharField(blank=True, default='', max_length=255)),
                ('organization_id', models.CharField(blank=True, default='', max_length=36)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_idempotency',
                'constraints': [models.UniqueConstraint(fields=('key', 'user_id'), name='uniq_idempotency_key_user')],
            },
        ),
        migrations.CreateModel(
            name='ProviderEvent',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='clerk', max_length=30)),
                ('external_event_id', models.CharField(max_length=150)),
                ('event_type', models.CharField(max_length=100)),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('duplicate', 'Duplicate')], default='received', max_length=30)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processing_started_at', models.DateTimeField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, default='', max_length=100)),
                ('error_summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auth_provider_event',
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_event_id'), name='uniq_provider_event')],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('organization_id', models.CharField(blank=True, default='', max_length=36)),
                ('location_id', models.CharField(blank=True, default='', max_length=36)),
                ('request_id', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('clerk_session_id', models.CharField(blank=True, default='', max_length=128)),
                ('severity', models.CharField(blank=True, default='info', max_length=20)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent_hash', models.CharField(blank=True, default='', max_length=64)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_events', to='authentication.authuser')),
            ],
            options={
                'db_table': 'auth_security_event',
                'indexes': [models.Index(fields=['user', '-occurred_at'], name='auth_securi_user_id_f24276_idx'), models.Index(fields=['event_type', '-occurred_at'], name='auth_securi_event_t_09fa30_idx')],
            },
        ),
        migrations.CreateModel(
            name='SessionProjection',
            fields=[
                ('id', models.CharField(default=apps.authentication.ids.new_uuid, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('clerk_session_id', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('ended', 'Ended'), ('expired', 'Expired'), ('unknown', 'Unknown')], default='active', max_length=20)),
                ('device_name', models.CharField(blank=True, default='', max_length=100)),
                ('device_platform', models.CharField(blank=True, default='', max_length=40)),
                ('browser_family', models.CharField(blank=True, default='', max_length=50)),
                ('app_version', models.CharField(blank=True, default='', max_length=30)),
                ('ip_hash', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent_hash', models.CharField(blank=True, default='', max_length=64)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='authentication.authuser')),
            ],
            options={
                'db_table': 'auth_session_projection',
                'indexes': [models.Index(fields=['user', '-last_seen_at'], name='auth_sessio_user_id_465aeb_idx')],
            },
        ),
    ]
