"""Auth module constants / event catalogue (MD §45, §55)."""

SECURITY_EVENT_TYPES = (
    "auth.application_bootstrap",
    "auth.session_seen",
    "auth.account_suspended",
    "auth.account_reactivated",
    "auth.invalid_token",
    "auth.invalid_authorized_party",
    "auth.organization_denied",
    "auth.location_denied",
    "auth.permission_denied",
    "auth.context_switched",
    "auth.webhook_received",
    "auth.webhook_processed",
    "auth.webhook_failed",
    "auth.webhook_duplicate",
)

# MD §45 — Authentication Error Catalogue
ERROR_CATALOGUE = {
    "authentication_required": 401,
    "invalid_token": 401,
    "expired_token": 401,
    "invalid_token_issuer": 401,
    "invalid_authorized_party": 401,
    "invalid_session": 401,
    "account_suspended": 403,
    "organization_access_denied": 403,
    "location_access_denied": 403,
    "permission_denied": 403,
    "context_not_found": 404,
    "idempotency_conflict": 409,
    "period_closed": 409,
    "stale_version": 409,
    "base_currency_locked": 409,
    "already_reversed": 409,
    "over_allocation": 409,
    "step_up_required": 403,
    "missing_context": 403,
    "cross_organization": 404,
    "journal_imbalanced": 422,
    "control_account_restricted": 422,
    "account_inactive": 422,
    "missing_rate": 422,
    "quote_not_convertible": 422,
    "po_not_convertible": 422,
    "already_matched": 409,
    "recon_imbalanced": 422,
    "approval_required": 409,
    "self_approve_forbidden": 403,
    "validation_error": 422,
    "rate_limit_exceeded": 429,
    "identity_dependency_unavailable": 503,
    "misconfigured": 503,
    "webhook_invalid": 401,
    "bootstrap_required": 401,
    "internal_error": 500,
}
