ACTIONS = (
    "finance.access.manage",
    "finance.settings.configure",
    "finance.account.maintain",
    "finance.journal.create",
    "finance.journal.post",
    "finance.journal.reverse",
    "finance.journal.read",
    "finance.report.view",
    "finance.period.lock",
    "finance.period.reopen",
    "finance.contact.maintain",
    "finance.item.maintain",
    "finance.invoice.create",
    "finance.document.post",
    "finance.payment.record",
    "finance.bill.create",
    "finance.document.approve",
)

ALL = list(ACTIONS)

PRESETS = {
    "owner": ALL,
    "finance_admin": [
        "finance.access.manage",
        "finance.settings.configure",
        "finance.account.maintain",
        "finance.journal.read",
        "finance.report.view",
        "finance.period.lock",
        "finance.contact.maintain",
        "finance.item.maintain",
        "finance.invoice.create",
        "finance.document.post",
        "finance.payment.record",
        "finance.bill.create",
        "finance.document.approve",
    ],
    "accountant": [
        "finance.journal.create",
        "finance.journal.post",
        "finance.journal.reverse",
        "finance.journal.read",
        "finance.report.view",
        "finance.period.lock",
        "finance.period.reopen",
        "finance.account.maintain",
        "finance.settings.configure",
        "finance.contact.maintain",
        "finance.item.maintain",
        "finance.invoice.create",
        "finance.document.post",
        "finance.payment.record",
        "finance.bill.create",
        "finance.document.approve",
    ],
    "sales_clerk": [
        "finance.contact.maintain",
        "finance.item.maintain",
        "finance.invoice.create",
        "finance.journal.read",
        "finance.report.view",
    ],
    "purchasing_clerk": [
        "finance.contact.maintain",
        "finance.item.maintain",
        "finance.bill.create",
        "finance.journal.read",
        "finance.report.view",
    ],
    "approver": ["finance.report.view", "finance.document.approve"],
    "viewer": ["finance.report.view", "finance.journal.read"],
}
